"""Create all teams + members from the PDF employee list"""
import json
import urllib.request

API = 'https://breakout-room-calibrator-1073587167150.us-central1.run.app'

members = [
    {"name":"Aditya Agarwal","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Akshay Deshmukh","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Aman Jalan","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Ansari Matiullah","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Asmita Sanjay Lawate","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Balaji Shinde","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Ganesh Somavanshi","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Kajal Kale","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Krutanjali Patil","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Muskan Daswani","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Neethu George","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Palash Somani","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Prem Duseja","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Ritesh Dilip Chaudhari","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Sayam Doshi","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Shubham Dhanawade","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Shubham Kothari","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Tushar Gurnani","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Tarun Ghumnani","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Tanvi Agrawal","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Sumair Sadiq","team_name":"Team Infrabeat","manager_name":"Team Infrabeat"},
    {"name":"Aditi Jain","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Aditi Singh","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Anjali Yadav","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Debarima Paul","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Fiza Rizvi","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Harshita Rajput","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Kshitija Daithankar","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Prashant Joshi","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Reena Agrawal","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Ronit Dilip Jadhav","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Sakshi Barwal","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Sakshi Jadhav","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Sayli Sonone","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Sima Kapil Jain","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Vaishali Malasi","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Vaishnavi Mande","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Meghana Budati","team_name":"Team Harshal","manager_name":"Team Harshal"},
    {"name":"Abhishek Sonar","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Akshata Kolekar","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Amol Bibwe","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Komal Kere","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Laxmi Khandelwal","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Mayank Panchal","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Vaishnavee Kalantri","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Radhika Rathi","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Pranay Oswal","team_name":"Team Accounts","manager_name":"Team Accounts"},
    {"name":"Arya Kulkarni","team_name":"Team Atish","manager_name":"Team Atish"},
    {"name":"Rutuja Dichwalkar","team_name":"Team Atish","manager_name":"Team Atish"},
    {"name":"Aastha Chandwani","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Aman Paul","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Geo Chirayath","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Kajal Yadav","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Om Bhombe","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Priyanka Mantri","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Rajat Sonkar","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Shailesh Chavan","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Shrikar Moolya","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Shubhangi Madhikar","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Shweta Gumnani","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Vikram Bisht","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Pruthvi Maurya","team_name":"Team Unimed","manager_name":"Team Unimed"},
    {"name":"Gagandeep Singh","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Harsh Jain","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Rukaiya Rangoonwala","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Satyam Rathi","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Manasvi More","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Bhumika Agarwal","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Shashank Channawar","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Yash Suthar","team_name":"Team Aaron","manager_name":"Team Aaron"},
    {"name":"Sakshi Ghodke","team_name":"Team Priya","manager_name":"Team Priya"},
    {"name":"Pooja Mahto","team_name":"Team Priya","manager_name":"Team Priya"},
    {"name":"Vidya Khandelwal","team_name":"Team Priya","manager_name":"Team Priya"},
    {"name":"Vidhi Khandelwal","team_name":"Team Priya","manager_name":"Team Priya"},
    {"name":"Meenal Suke","team_name":"Team Priya","manager_name":"Team Priya"},
    {"name":"Arya Magar","team_name":"Team Priya","manager_name":"Team Priya"},
    {"name":"Chetan Ingale","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Adwait Phadke","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Shashi Ranjan","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Ashish Singh","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Himanshu Thard","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Pranav Babras","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Adesh Kumbhar","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Raghvendra Lamhaji","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Suryaprakash G P","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Sayoni Sengupta","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Niraj Goythale","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Akhil Tidke","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Swapnil Ingle","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Nikhil Khanzode","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Mazhar Khan","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Avinash Gunti","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Mohammed Salman Imtiaz","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Sahil Kulkarni","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Abhijeet Debe","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Atharva Gajare","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Brijesh Saini","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Pinak Wadekar","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Jui Yadav","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Meghraj Reddy","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Bhakti Patil","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Pratik Patil","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Jayant Bankar","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Salman Hundekari","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Chethan R","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Akash Jadhav","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Daksha Dhamal","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Subham Barua","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Shubham Raj","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Vishal Gawali","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Hari Kiran Lanka","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Dhiraj Bhoknal","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Pradip Bagate","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Srushti Dhamal","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Ashutosh Bhivsankar","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Vedant Dipak Tambe","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Vignesh Naik","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Pratik Adak","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Vaibhavi Sayare","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Jayesh Patil","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Vaishnavi Patil","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Arpita Patil","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Jinal Patil","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Yatin Phalke","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Swati","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Veena Baghvat","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Alisha","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Sidhodhan Sable","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Aditi Chavan","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"JP Singh","team_name":"Infrabeat Client","manager_name":"Infrabeat Client"},
    {"name":"Aarti","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Mrunal","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Ishwar","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Sanchita Ghosh","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Hemlata Reddy","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Nayana","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Nikita","team_name":"Vridam","manager_name":"Vridam"},
    {"name":"Himal Goyal","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Shubham Jain","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Sanjeevani Razdan","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Indrayani","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Puneet Kumar","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Rajat Mishra","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Rohit Choudhary","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Mamta Badade","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Anurag Gaigowal","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Athrava","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Harin Shah","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Soumaya","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Renu Raut","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Anubhav Singh","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Tanishk Jalan","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Chinmay Deshpande","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Rohit Girase","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Yashasvi Dhakate","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Gayatri Naidu","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Tejas Shirke","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Greeshma Kadam","team_name":"Accurest Client","manager_name":"Accurest Client"},
    {"name":"Kuldeep Ruchandani","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Amruta A Shete","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Kamakshi Gorwadkar","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Krishna Ratkalkar","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Kritika Jain","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Megha Sharma","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Nandini Shah","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Pallavi Jain","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Pragy Jadhav","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Rajesh Sharma","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Sakshi Mehadiya","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Shruti Phadke","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Sneha Patil","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Tamonasha Acharjee","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Yushita Hardeniya","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Ruchita Shah","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Gayatri Dabi","team_name":"KPRC Client-Kuldeep Sir","manager_name":"KPRC Client-Kuldeep Sir"},
    {"name":"Pawan Sir","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Aniket Parcharne","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Chetna Tolani","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Khushbu Acharya","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Mitali Gupta","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Mrunal Divakar","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Pooja Wani","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Prachi Bhandari","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Rahul Agarwal","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Rutuja More","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Shriram","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Shweta Tulsani","team_name":"KPRC Client-Pawan Sir","manager_name":"KPRC Client-Pawan Sir"},
    {"name":"Yogendra Sharma","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Aditi Nagpure","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Nikhil Shahu","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Payal Talaviya","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Raghav Arora","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Rena Oswal","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Samarth Gangane","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Shivani Sharma","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Vaishnavi Vedua","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Vishwa Patel","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
    {"name":"Vrunda Joshi","team_name":"KPRC Client-Yogendra Sir","manager_name":"KPRC Client-Yogendra Sir"},
]

print(f"Total members: {len(members)}")
teams = {}
for m in members:
    teams.setdefault(m['team_name'], []).append(m['name'])
for t, ms in sorted(teams.items()):
    print(f"  {t}: {len(ms)}")

# Call API
payload = json.dumps({"members": members}).encode('utf-8')
req = urllib.request.Request(f'{API}/teams/bulk-import', data=payload,
                             headers={'Content-Type': 'application/json'}, method='POST')
resp = urllib.request.urlopen(req, timeout=120)
result = json.loads(resp.read().decode())
print(f"\nAPI Result: {json.dumps(result)}")
